services:
  chartwebapp:
    image: chartwebapp
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh", "-c", "echo 'Waiting 30s for MySQL...'; sleep 30; dotnet ChartWebApp.dll"]
    ports:
      - "9800:80"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: chart_app
      MYSQL_DATABASE: chart_app
      MYSQL_USER: chart_app
      MYSQL_PASSWORD: chart_app
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s